// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Z-MrTrc57xL0ofrXtu2u9Q7u8cQkXbE',
    appId: '1:397620043905:web:a461f15f9e932eebfdad80',
    messagingSenderId: '397620043905',
    projectId: 'tennis-club-app-fb311',
    authDomain: 'tennis-club-app-fb311.firebaseapp.com',
    storageBucket: 'tennis-club-app-fb311.firebasestorage.app',
    measurementId: 'G-LF1V16FNC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDupjTNNPToXJOQwq--SoPkYMPZOPOy_Hw',
    appId: '1:397620043905:android:4236a25f8f0ea64dfdad80',
    messagingSenderId: '397620043905',
    projectId: 'tennis-club-app-fb311',
    storageBucket: 'tennis-club-app-fb311.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuhob5Ik5YSNBYoR-G38-gnQgwogoZxUs',
    appId: '1:397620043905:ios:75b00e0a8a5f03e8fdad80',
    messagingSenderId: '397620043905',
    projectId: 'tennis-club-app-fb311',
    storageBucket: 'tennis-club-app-fb311.firebasestorage.app',
    iosBundleId: 'com.example.tennisClubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuhob5Ik5YSNBYoR-G38-gnQgwogoZxUs',
    appId: '1:397620043905:ios:75b00e0a8a5f03e8fdad80',
    messagingSenderId: '397620043905',
    projectId: 'tennis-club-app-fb311',
    storageBucket: 'tennis-club-app-fb311.firebasestorage.app',
    iosBundleId: 'com.example.tennisClubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Z-MrTrc57xL0ofrXtu2u9Q7u8cQkXbE',
    appId: '1:397620043905:web:0d9350c642f59ee2fdad80',
    messagingSenderId: '397620043905',
    projectId: 'tennis-club-app-fb311',
    authDomain: 'tennis-club-app-fb311.firebaseapp.com',
    storageBucket: 'tennis-club-app-fb311.firebasestorage.app',
    measurementId: 'G-192CK9168P',
  );
}
